### ISSUE TITLE
Items not equipable

### ISSUE THREAD

**Issue by Maddremor** [lensvol/fl-assorted-cats#3]
Seems like something with the FL interface has changed as to make the items in the bar not equippable. This is inconvenient for wanting to equip something useful. Not sure if this is something that can be fixed (or should be fixed if it was an intentional change by FBG), but here we are.

**Comment by lensvol** [comment]
Yes, I can see that in the recent update they reworked equipment UI internals and that sadly breaks our fragile hacks. I will look into fixing this, thank you!

**Comment by Maddremor** [comment]
I do kind of get why they would do that seeing as it can be used as a substitute for outfit slots.

**Comment by lensvol** [comment]
I do not think that was intentional, just a usual refactoring that breaks things.

**Comment by Maddremor** [comment]
Alright, that looks like it's working for me. Great job!
