### ISSUE TITLE
Addon does not support new equipment slots

### ISSUE THREAD

**Issue by Maddremor** [lensvol/fl-assorted-cats#4]
As of a mid-week [patch](https://community.failbettergames.com/t/patch-notes/19404/433) new equipment slots have been added to the game. Adornments, crew, and luggage can already be filled, while the airship slot is not visible in the UI for lack of a ship being acquirable yet (but whose slot is visible in the character profile). None of these are included in the custom section added by this addon at the time of writing.

**Comment by lensvol** [comment]
I was afraid of that, will get right on to it.

**Comment by lensvol** [comment]
Fixed in https://github.com/lensvol/fl-assorted-cats/commit/be1c835bd27b0fa40d565aa9b02cd15240f0a570, updates should trickle down through app stores.
